# Start

## Here We will see Numpy Methods for Slicing and Stacking and Boolean indexing

For Slicing we have [:] 

For Stacking we have 2 methods 

- vstack
- hstack

These 2 methods are used for Stack/ combine 2 arrays based on vartical / Horizontal

**reshape()**

It is used to restructure an Array with specified formate

Now Lets say you have a big Array and you wanted to split it in chunks you can do using 2 functions

- hsplit
- vsplit

these 2 functions are responsibility for spliting a larger Array into different chunks..

### Indexing with Boolean Array

This is a crucial or Very Important concept

if you have a 2D Array 
```
ex:- 
    a = [Array]
    b = a>4
    #so Now b having an boolean array conisting of respective values
    a[b] # this is important 
    # the true values we have we will get the values
    
```

In [4]:
import numpy as np

arr = np.arange(20)
print(arr)
arr.reshape(4, -1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [7]:
a = np.arange(12).reshape(3,-1)
print(a)

b= np.arange(12,24).reshape(3,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [11]:
# vstack / hstack
varr = np.vstack((a,b))

print(varr)

harr = np.hstack((a,b))

print(harr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]


In [15]:
bigarr = np.arange(40).reshape(2,-1)
print(bigarr)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]]


In [26]:
harr = np.hsplit(bigarr, 10) # these number are you need to think on it will split on Horizontal so what would be number 

print(harr)

varr = np.vsplit(bigarr, 2)

print(varr)

[array([[ 0,  1],
       [20, 21]]), array([[ 2,  3],
       [22, 23]]), array([[ 4,  5],
       [24, 25]]), array([[ 6,  7],
       [26, 27]]), array([[ 8,  9],
       [28, 29]]), array([[10, 11],
       [30, 31]]), array([[12, 13],
       [32, 33]]), array([[14, 15],
       [34, 35]]), array([[16, 17],
       [36, 37]]), array([[18, 19],
       [38, 39]])]
[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]]), array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39]])]


In [27]:
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [28]:
b = a < 5

print(b)

[[ True  True  True  True]
 [ True False False False]
 [False False False False]]


In [34]:
a[b] = -1

In [35]:
a


array([[-1, -1, -1, -1],
       [-1,  5,  6,  7],
       [ 8,  9, 10, 11]])

## Completed

#### By Ashu, Inspired by Codebasic