## Start

### This is more about iterrating numpy arrar

We can use Normal for loop to do the job but, we can also use **nditer** for the same

it has lot many other functionalities also

[Link For Numpy nditer](https://numpy.org/doc/stable/reference/generated/numpy.nditer.html) Look for More Detailed Information.



In [3]:
import numpy as np

a = np.arange(12, 24, 1).reshape(3,4)
print(a)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [5]:
for x in a.flatten():
    print(x)

12
13
14
15
16
17
18
19
20
21
22
23


In [7]:
for x in np.nditer(a):
    print(x)

12
13
14
15
16
17
18
19
20
21
22
23


In [12]:
for x in np.nditer(a, order="C", flags=["external_loop"]):
    print(x)

[12 13 14 15 16 17 18 19 20 21 22 23]


In [11]:
for x in np.nditer(a, order='F', flags=["external_loop"]):
    print(x)

[12 16 20]
[13 17 21]
[14 18 22]
[15 19 23]


## Completed

#### By Ashu, inspired By Codebasic